---
  name: Build and Deploy Vite React App to S3 and CloudFront
  on:
    push:
      branches: [main]
  permissions:
    id-token: write
    contents: read
  jobs:
    build-and-deploy:
      name: Build and Deploy
      runs-on: ubuntu-latest
  
      env:
        VITE_DIST: dist
        AWS_REGION: us-east-1
        S3_BUCKET: learnify-ui-s3-cloudfront
        CLOUDFRONT_DISTRIBUTION_ID: E223Z4I8M5YCQI
        NODE_VERSION: '18'
  
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: ${{ env.NODE_VERSION }}
            cache: 'npm'

        - name: Configure AWS credentials from AWS account
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::132930376828:role/oidc-aws-github
            aws-region: ${{ env.AWS_REGION }}

        - name: Install Dependencies
          run: |
            node --version
            npm ci

        - name: Run type check
          run: npm run type-check

        - name: Run linting
          run: npm run lint

        - name: Build Static Website
          run: npm run build
          env:
            CI: true

        - name: Copy files to S3 with optimized cache headers
          run: |
            # Upload assets with long cache (1 year)
            aws s3 sync --delete ${{ env.VITE_DIST }} s3://${{ env.S3_BUCKET }} \
              --cache-control "public, max-age=31536000" \
              --exclude "*.html" \
              --exclude "*.json"
            
            # Upload HTML and JSON files with short cache (5 minutes)
            aws s3 sync ${{ env.VITE_DIST }} s3://${{ env.S3_BUCKET }} \
              --cache-control "public, max-age=300" \
              --include "*.html" \
              --include "*.json"

        - name: Invalidate CloudFront Distribution
          run: |
            aws cloudfront create-invalidation \
              --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
              --paths "/*"